### ISSUE TITLE
void

### ISSUE THREAD

**Issue by ghost** [infinitex-tech/infeos#7]

**Comment by DimitarSD** [comment]
Some of the logic behind infeos use shell scripts to interact with Docker. Unfortunately, it's not possible to run shell scripts under Windows if Cygwin or something similar is installed.

However, we'll check if there is an easier and faster solution.

**Comment by lazaridiscom** [comment]
> Unfortunately, it's not possible 

don't say this. I never met the necessity for cygwin on windows, especially when using docker.

**Comment by lazaridiscom** [comment]
and as a sidenote: you should not close issues that fast. keep them open, possibly someone can provide a solution

**Comment by DimitarSD** [comment]
> > Unfortunately, it's not possible
> 
> don't say this. I never met the necessity for cygwin on windows, especially when using docker.

I'm not saying that we need Cygwin for Docker. The shell scripts are executed under Windows environment mostly in cmd.exe. CMD uses a different syntax to execute commands compared to the terminal in Mac OS.

**Comment by ghost** [comment]
My fault, i should not go into dicussions for an alpha-state tool. me out. I'll write the tests in BOOST/C++ for now.
