### ISSUE TITLE
Fail to generate ABI from default `universe` project

### ISSUE THREAD

**Issue by conr2d** [infinitex-tech/infeos#9]
**Version of infeos**
0.1.33

**Describe the bug**
Fail to generate ABI from default `universe` project

**To Reproduce**
1. infeos init .
2. infeos compile abi

**Expected behavior**
`universe.abi` is generated

**Screenshots**
![image](https://user-images.githubusercontent.com/9255652/55136787-a94c9200-5172-11e9-9479-1381a1ab8d0f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
It seems that `eos-dev-infeos` docker image using EOSIO.CDT 1.5.0 (tag is named like "eos1.6.1-cdt1.5.0 "), but I could generate ABI with CDT 1.5.0 & 1.6.1 installed in native.

**Comment by DimitarSD** [comment]
Hi @conr2d! Is the ABI empty or not generated at all?

**Comment by conr2d** [comment]
Hi @DimitarSD 
More accurately, ABI file is generated, but empty. With eosio.cdt v1.5.0, explicit option `--contract` is required to generate ABI. It seems that cdt v1.6.1 can generate ABI correctly without this option.

BTW, I'm impressed with your work. Thanks for your efforts. If you don't mind, I would send patches for feature enhancements or bug fixes. :)

**Comment by DimitarSD** [comment]
Thanks @conr2d. Yeah, with the new version of CDT (1.6.1) a lot of new things were introduced/fixed.

I just test it with `--contract` and generates only the actions. I'll do more tests later today to see if I'll be able to generate the rest of data.

And of course, feel free to send patches for feature enhancements or bug fixes. I see that you work on Ubuntu so it would be really helpful as from our side it's a bit hard to test infeos under Linux :)

**Comment by conr2d** [comment]
https://github.com/EOSIO/eosio.cdt/blob/v1.5.0/tools/abigen/eosio-abigen.cpp.in#L509-L514

`eosio-abigen` in CDT v1.5.0 requires the name of table and contract. As far as I know, CDT v1.6.1 doesn't use `eosio-abigen` any more, but linker will do the same thing. I pushed  an additional commit to my PR to generate ABI with CDT v1.5.0.

**Comment by CaliosD** [comment]
I wonder if this issue has been fixed, 'cause I've also come across the same problem. :P
